name: dotnet package

on: [push, pull_request]

jobs:
  build_linux:

    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    env:
      Solution_Name: Agency.sln                         
      Test_Project_Path: Agency.Test\Agency.Test.csproj

    steps:
      - uses: actions/checkout@v2

      # Install the .NET Core workload
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Install any dependencies
      - name: Install dependencies
        run: dotnet restore

      # Install the .NET Core workload
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Install the .NET Core workload
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
       matrix:
         dotnet-version: ['5.0.x' ]

    env:
       Solution_Name: Agency.sln                         
       Test_Project_Path: Agency.Test\Agency.Test.csproj

    steps:
      - uses: actions/checkout@v2

      # Install the .NET Core workload
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Install any dependencies
      - name: Install dependencies
        run: dotnet restore

      # Install the .NET Core workload
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Install the .NET Core workload
      - name: Test
        run: dotnet test --no-restore --verbosity normal