name: dotnet package

on: [push, pull_request]

jobs:
  build_linux:

    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    env:
      Solution_Name: Agency.sln                         
      Test_Project_Path: Agency.Test\Agency.Test.csproj

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  build_windows:
    name: Build Windows
    runs-on: ubuntu-latest
    strategy:
       matrix:
         dotnet-version: ['5.0.x' ]

    env:
       Solution_Name: Agency.sln                         
       Test_Project_Path: Agency.Test\Agency.Test.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: ${{ matrix.dotnet-version }}

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}